# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DcEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('baja_time', models.PositiveIntegerField()),
                ('baja_score', models.PositiveIntegerField()),
                ('toike_cannon_score', models.PositiveIntegerField()),
                ('wise_score', models.PositiveIntegerField()),
                ('hpv_score', models.PositiveIntegerField()),
                ('team', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
            ],
        ),
    ]
