# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-25 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcentry',
            name='baja_score',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dcentry',
            name='baja_time',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dcentry',
            name='hpv_score',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dcentry',
            name='score',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dcentry',
            name='toike_cannon_score',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dcentry',
            name='wise_score',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
