# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-25 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmentry',
            name='score',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
